  
DROP TABLE IF EXISTS PRODUCT;

CREATE TABLE PRODUCT (
  product_Id INT AUTO_INCREMENT  PRIMARY KEY,
  product_Name VARCHAR(250) NOT NULL,
  description VARCHAR(250) NOT NULL,
  quantity INT NOT NULL,
  price DOUBLE NOT NULL
);